FROM openjdk:24-slim-bookworm AS stage0
RUN apt update -y
WORKDIR /app
ADD https://github.com/Greeshma594/build-artifactory/raw/refs/heads/main/helloworld-1.0-SNAPSHOT.war .
ENTRYPOINT ["java" , "-jar" , "helloworld-1.0-SNAPSHOT.war"]
