FROM tomcat:9-jdk11-openjdk-slim AS stage0
RUN apt update -y
WORKDIR /app
ADD https://github.com/Greeshma594/build-artifactory/raw/refs/heads/main/helloworld-1.0-SNAPSHOT.war .
COPY helloworld-1.0-SNAPSHOT.war /usr/local/tomcat/webapps/
EXPOSE 8080
CMD ["catalina.sh", "run"]
